version: "3.4"

services:
  nginx-proxy:
    container_name: nginx-proxy-${LANG}
    build:
      context: .
      dockerfile: environment/nginx-fastcgi-pass/alpine/Dockerfile
    restart: always
    working_dir: /var/www/public
    volumes:
      - .:/var/www
      - ./environment/nginx-fastcgi-pass/alpine/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: host

  php-fpm:
    container_name: php-fpm-upstream
    build:
      context: .
      dockerfile: environment/php-fpm/Dockerfile
    working_dir: /var/www
    volumes:
      - ./src/php:/var/www/public
      - ./environment/php-fpm/php-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./environment/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    network_mode: host

